apiVersion: v1
kind: Secret
metadata:
  name: db-secret
  namespace: k8s-assignment
  labels:
    app: k8s-assignment
type: Opaque
data:
  # base64 encoded: echo -n 'appuser' | base64 => YXBwdXNlcg==
  DB_USER: YXBwdXNlcg==
  # base64 encoded: echo -n 'apppassword' | base64 => YXBwcGFzc3dvcmQ=
  DB_PASSWORD: YXBwcGFzc3dvcmQ=
